import React, { useState, useMemo } from 'react';
import { Panel } from '../ui/Panel';
import { DatePicker } from '../ui/DatePicker';
import {
  Download, Sparkles, Loader2, CalendarDays, PhoneCall,
  ListTodo, BarChart3, Users, ClipboardList,
  UserCheck, UserMinus, PhoneForwarded
} from 'lucide-react';
import { generateDailyReportWithDeepSeek } from '../../services/api';
import { DEEPSEEK_API_KEY } from '../../utils/constants';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// ── Markdown table parser ──────────────────────────────────────────────────────
function parseMarkdownTable(md) {
  const lines = md.trim().split('\n').filter(l => l.trim());
  const rows = lines.filter(l => !l.match(/^\|[-| ]+\|$/));
  return rows.map(r => r.split('|').filter((_, i, a) => i > 0 && i < a.length - 1).map(c => c.trim()));
}

// ── Render a markdown section as JSX ─────────────────────────────────────────
function MarkdownSection({ text, color }) {
  if (!text) return null;
  const lines = text.split('\n');
  const elements = [];
  let tableLines = [];
  let inTable = false;

  const flushTable = (key) => {
    if (tableLines.length < 2) { tableLines = []; inTable = false; return; }
    const parsed = parseMarkdownTable(tableLines.join('\n'));
    const [header, ...body] = parsed;
    elements.push(
      <div key={key} style={{ overflowX: 'auto', marginBottom: '12px' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
          <thead>
            <tr>{header.map((h, i) => (
              <th key={i} style={{ padding: '8px 12px', background: 'rgba(255,255,255,0.05)', color: '#fff', fontWeight: '700', textAlign: 'left', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>{h}</th>
            ))}</tr>
          </thead>
          <tbody>
            {body.map((row, ri) => (
              <tr key={ri} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                {row.map((cell, ci) => (
                  <td key={ci} style={{ padding: '7px 12px', color: 'rgba(255,255,255,0.6)', fontSize: '13px' }}>{cell}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
    tableLines = []; inTable = false;
  };

  lines.forEach((line, idx) => {
    if (line.startsWith('|')) {
      inTable = true;
      tableLines.push(line);
    } else {
      if (inTable) flushTable(`tbl-${idx}`);
      if (line.startsWith('## ')) {
        elements.push(<h3 key={idx} style={{ color, fontSize: '15px', fontWeight: '700', marginBottom: '6px', marginTop: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: color, flexShrink: 0 }} />
          {line.replace('## ', '')}
        </h3>);
      } else if (line.startsWith('### ')) {
        elements.push(<h4 key={idx} style={{ color: 'rgba(255,255,255,0.7)', fontSize: '13px', fontWeight: '700', marginBottom: '4px', marginTop: '10px' }}>{line.replace('### ', '')}</h4>);
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        elements.push(<li key={idx} style={{ color: 'rgba(255,255,255,0.6)', fontSize: '13px', lineHeight: '1.6', marginLeft: '16px', marginBottom: '2px' }}>{line.replace(/^[-*] /, '')}</li>);
      } else if (line.trim() !== '') {
        elements.push(<p key={idx} style={{ color: 'rgba(255,255,255,0.6)', fontSize: '13px', lineHeight: '1.6', marginBottom: '6px' }}>{line}</p>);
      }
    }
  });
  if (inTable) flushTable('tbl-last');
  return <div>{elements}</div>;
}

// ── PDF Generator ─────────────────────────────────────────────────────────────
function generatePDF(report, stats, searchDate) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  let y = 20;

  const addPage = () => { doc.addPage(); y = 20; };
  const checkY = (needed = 20) => { if (y + needed > 270) addPage(); };

  // Header bar
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, W, 14, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Voice Campaign Performance Report', W / 2, 9, { align: 'center' });

  y = 22;
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Report Date: ${searchDate}   |   Generated by CallingGen AI`, W / 2, y, { align: 'center' });
  y += 8;

  // Stats summary bar
  autoTable(doc, {
    startY: y,
    head: [['Total Calls', 'Completed', 'Interested', 'Not Interested', 'Busy', 'Rescheduled']],
    body: [[stats.total, stats.completed, stats.interested, stats.notInterested, stats.busy, stats.rescheduled]],
    styles: { fontSize: 9, halign: 'center' },
    headStyles: { fillColor: [99, 102, 241], textColor: 255, fontStyle: 'bold' },
    bodyStyles: { fillColor: [245, 245, 255] },
    margin: { left: 14, right: 14 },
  });
  y = doc.lastAutoTable.finalY + 10;

  // Parse and render sections from markdown
  const sections = report.fullReport.split(/\n(?=## \d+\.)/).filter(Boolean);

  sections.forEach((section) => {
    const lines = section.trim().split('\n');
    const heading = lines[0].replace(/^## \d+\.\s*/, '').trim();
    const body = lines.slice(1).join('\n').trim();

    checkY(14);
    doc.setFillColor(235, 233, 255);
    doc.rect(14, y - 4, W - 28, 9, 'F');
    doc.setTextColor(60, 40, 180);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(heading, 16, y + 2);
    y += 10;

    // Detect table blocks
    const tableMatch = body.match(/(\|.+\n)+/g);
    if (tableMatch) {
      tableMatch.forEach(tbl => {
        const rows = parseMarkdownTable(tbl);
        if (rows.length < 2) return;
        const [head, ...bodyRows] = rows;
        checkY(20);
        autoTable(doc, {
          startY: y,
          head: [head],
          body: bodyRows,
          styles: { fontSize: 8, cellPadding: 3 },
          headStyles: { fillColor: [139, 92, 246], textColor: 255, fontStyle: 'bold' },
          alternateRowStyles: { fillColor: [248, 248, 255] },
          margin: { left: 14, right: 14 },
        });
        y = doc.lastAutoTable.finalY + 6;
      });

      // Narrative outside table
      const narrative = body.replace(/(\|.+\n?)+/g, '').trim();
      if (narrative) {
        const wrapped = doc.splitTextToSize(narrative.replace(/^[-*] /gm, '• '), W - 30);
        checkY(wrapped.length * 5);
        doc.setTextColor(60, 60, 60);
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'normal');
        doc.text(wrapped, 14, y);
        y += wrapped.length * 5 + 4;
      }
    } else {
      const clean = body.replace(/^[-*] /gm, '• ').replace(/\*\*/g, '');
      const wrapped = doc.splitTextToSize(clean, W - 30);
      checkY(wrapped.length * 5);
      doc.setTextColor(60, 60, 60);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.text(wrapped, 14, y);
      y += wrapped.length * 5 + 6;
    }
  });

  // Footer on all pages
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(`CallingGen AI  |  Confidential  |  Page ${p} of ${totalPages}`, W / 2, 290, { align: 'center' });
  }

  doc.save(`Campaign_Report_${searchDate}.pdf`);
}

// ── Main Component ─────────────────────────────────────────────────────────────
export const ReportView = ({
  contacts,
  agentId,
  searchDate,
  setSearchDate,
  stats: globalStats,
  activeView,
  setActiveView
}) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [report, setReport] = useState(null);

  const activeContacts = useMemo(() =>
    agentId ? contacts.filter(c => c.agentId === agentId) : contacts,
    [contacts, agentId]
  );
  const dayContacts = useMemo(() =>
    activeContacts.filter(c => c.date === searchDate),
    [activeContacts, searchDate]
  );

  const total         = dayContacts.length;
  const completed     = dayContacts.filter(c => c.status === 'completed' || c.status === 'called').length;
  const busy          = dayContacts.filter(c => (c.response || '').toLowerCase().includes('busy')).length;
  const interested    = dayContacts.filter(c => c.leadCategory === 'interested' || ((c.response || '').toLowerCase().includes('interested') && !(c.response || '').toLowerCase().includes('not interested'))).length;
  const notInterested = dayContacts.filter(c => c.leadCategory === 'not_interested' || (c.response || '').toLowerCase().includes('not interested')).length;
  const rescheduled   = dayContacts.filter(c => c.leadCategory === 'reschedule' || (c.response || '').toLowerCase().includes('reschedule')).length;

  const currentStats = { total, completed, busy, interested, notInterested, rescheduled };

  // Agent breakdown
  const agentMap = {};
  dayContacts.forEach(c => {
    const key = c.agentId || 'Unknown';
    if (!agentMap[key]) agentMap[key] = { name: c.agentName || key, calls: 0, interested: 0, notInterested: 0, rescheduled: 0 };
    agentMap[key].calls++;
    if (c.leadCategory === 'interested') agentMap[key].interested++;
    if (c.leadCategory === 'not_interested') agentMap[key].notInterested++;
    if (c.leadCategory === 'reschedule') agentMap[key].rescheduled++;
  });

  // Lead categories
  const leadCategories = {};
  dayContacts.forEach(c => {
    const cat = c.leadCategory || 'uncategorized';
    leadCategories[cat] = (leadCategories[cat] || 0) + 1;
  });

  // Exam stream breakdown
  const streamMap = {};
  dayContacts.forEach(c => {
    if (c.stream) streamMap[c.stream] = (streamMap[c.stream] || 0) + 1;
  });

  const handleGenerate = async () => {
    if (total === 0) { alert('No calls found for the selected date.'); return; }
    setIsGenerating(true);

    const summaries = dayContacts
      .filter(c => c.summary && c.summary.trim() !== '')
      .map(c => `- ${c.name}: ${c.summary}`)
      .slice(0, 15);

    const agentRows = Object.values(agentMap)
      .map(a => `| ${a.name} | - | ${a.calls} | Not provided | Not provided | Not provided |`)
      .join('\n');

    const leadRows = Object.entries(leadCategories)
      .map(([cat, count]) => `| ${cat} | ${count} | - |`)
      .join('\n');

    const streamRows = Object.entries(streamMap).length > 0
      ? Object.entries(streamMap).map(([s, c]) => `| ${s} | ${c} | - |`).join('\n')
      : '| Not provided | - | - |';

    const systemPrompt = `You are a technical report generator specializing in AI voice campaign performance reports.
Your output must follow this EXACT structure with these EXACT section headings:

## 1. Executive Summary
## 2. Key Performance Highlights
## 3. Agent-wise Performance Breakdown
## 4. Agent Insights
## 5. Lead Generation & Quality Analysis
## 6. Cost Efficiency Analysis
## 7. Inbound Agent Performance
## 8. Stream-wise Lead Distribution
## 9. Recommendations & Next Steps
## 10. Summary

Rules:
- Use professional business English
- NEVER invent data. If a metric is missing, state "Not provided"
- Format tables using markdown pipe syntax
- Do NOT include any time, duration, or timestamp data anywhere
- Keep total length under 1200 words
- Temperature: keep output consistent and factual`;

    const userPrompt = `Generate a campaign performance report for the following data:

CALL STATISTICS:
- Total Calls: ${total}
- Completed: ${completed}
- Interested: ${interested}
- Not Interested: ${notInterested}
- Busy: ${busy}
- Rescheduled: ${rescheduled}

AGENT BREAKDOWN:
| Agent Name | Focus Area | Total Calls | Total Cost | Total Duration | Avg Cost/Call |
|---|---|---|---|---|---|
${agentRows || '| Not provided | - | - | - | - | - |'}

LEAD CATEGORIES:
| Category | Count | Meaning |
|---|---|---|
${leadRows || '| Not provided | - | - |'}

STREAM-WISE DISTRIBUTION:
| Exam Stream | Leads | Notes |
|---|---|---|
${streamRows}

CALL SUMMARIES (sample):
${summaries.length > 0 ? summaries.join('\n') : 'Not provided'}

Do not include any time-based metrics. Focus only on call counts, lead quality, agent performance, and business recommendations.`;

    try {
      const generated = await generateDailyReportWithDeepSeek(
        DEEPSEEK_API_KEY,
        currentStats,
        summaries,
        systemPrompt,
        userPrompt
      );
      setReport(generated);
    } catch (e) {
      alert('Failed to generate report. Please try again.');
    }
    setIsGenerating(false);
  };

  const handleDownloadPDF = () => {
    if (!report) return;
    generatePDF(report, currentStats, searchDate);
  };

  const navItems = [
    { id: 'calendar',  label: 'Dashboard',    icon: <CalendarDays size={18} /> },
    { id: 'manager',   label: 'Call Manager', icon: <PhoneCall size={18} /> },
    { id: 'details',   label: 'Call Details', icon: <ListTodo size={18} /> },
    { id: 'responses', label: 'Responses',    icon: <BarChart3 size={18} /> },
    { id: 'leads',     label: 'Leads',        icon: <Users size={18} /> },
    { id: 'report',    label: 'Report',       icon: <ClipboardList size={18} /> },
  ];

  const SECTION_COLORS = [
    '#8b5cf6','#6366f1','#a78bfa','#10b981',
    '#34d399','#f59e0b','#60a5fa','#ec4899','#14b8a6','#f97316'
  ];

  return (
    <div className="report-page-container" style={{ paddingTop: '20px' }}>
      <div className="report-layout-wrapper">

        {/* ── LEFT COLUMN ── */}
        <div className="report-left-column">
          <div className="details-nav-matrix">
            {navItems.map((item) => (
              <div
                key={item.id}
                className={`nav-matrix-item ${activeView === item.id ? 'active' : ''}`}
                onClick={() => setActiveView(item.id)}
              >
                <div className="nav-matrix-icon">{item.icon}</div>
                <span className="nav-matrix-label">{item.label}</span>
              </div>
            ))}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '8px', marginTop: '20px', width: '100%' }}>
            {[
              { icon: <PhoneCall size={14} />, color: '#6366f1', value: total,         label: 'Total Calls'    },
              { icon: <UserCheck size={14} />, color: '#4ade80', value: interested,    label: 'Interested'     },
              { icon: <UserMinus size={14} />, color: '#f87171', value: notInterested, label: 'Not Interested' },
              { icon: <PhoneForwarded size={14} />, color: '#fbbf24', value: rescheduled, label: 'Reschedule'  },
            ].map(({ icon, color, value, label }) => (
              <div key={label} className="mini-metric-card" style={{ padding: '10px 16px', height: '44px', flexDirection: 'row', alignItems: 'center', gap: '12px', justifyContent: 'flex-start' }}>
                <div className="metric-icon-wrap" style={{ color, width: '28px', height: '28px', flexShrink: 0 }}>{icon}</div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span className="metric-value" style={{ fontSize: '16px', fontWeight: '800' }}>{value}</span>
                  <span className="metric-label" style={{ fontSize: '12px', fontWeight: '600', opacity: 0.6 }}>{label}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ── RIGHT COLUMN ── */}
        <div className="report-right-column">
          <div style={{ display: 'flex', flexDirection: 'column', height: '100%', gap: '20px' }}>
            <Panel style={{ flex: 1, minHeight: 0, borderRadius: '24px', overflow: 'hidden' }}>
              <div className="panel-body" style={{ height: '100%', padding: '32px', display: 'flex', flexDirection: 'column', borderRadius: '0 0 24px 24px' }}>

                {/* Header */}
                <div style={{ textAlign: 'center', marginBottom: '24px' }}>
                  <h2 style={{ fontSize: '32px', fontWeight: '800', color: '#fff', marginBottom: '8px', letterSpacing: '-0.04em' }}>
                    AI Report Generator
                  </h2>
                  <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '14px' }}>
                    Generates a 10-section structured PDF report — no time data, facts only.
                  </p>
                </div>

                {/* Controls */}
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '16px', marginBottom: '24px', background: 'rgba(255,255,255,0.03)', padding: '12px 24px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.06)', backdropFilter: 'blur(10px)', flexWrap: 'wrap' }}>
                  <DatePicker value={searchDate} onChange={setSearchDate} />

                  <button
                    onClick={handleGenerate}
                    disabled={isGenerating || total === 0}
                    style={{ background: isGenerating ? 'rgba(139,92,246,0.2)' : 'linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)', border: 'none', padding: '10px 24px', borderRadius: '10px', color: '#fff', fontSize: '14px', fontWeight: '700', cursor: (isGenerating || total === 0) ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', gap: '8px', boxShadow: isGenerating ? 'none' : '0 4px 15px rgba(99,102,241,0.2)', transition: 'all 0.3s ease', opacity: total === 0 ? 0.5 : 1, whiteSpace: 'nowrap' }}
                  >
                    {isGenerating ? <Loader2 className="animate-spin" size={18} /> : <Sparkles size={18} />}
                    {isGenerating ? 'Analyzing...' : 'Generate AI Report'}
                  </button>

                  <button
                    onClick={handleDownloadPDF}
                    disabled={!report}
                    style={{ background: report ? 'linear-gradient(135deg, #10b981, #059669)' : 'rgba(255,255,255,0.05)', border: report ? 'none' : '1px solid rgba(255,255,255,0.1)', padding: '10px 18px', borderRadius: '10px', color: '#fff', fontSize: '13px', fontWeight: '600', cursor: !report ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.2s', whiteSpace: 'nowrap', opacity: !report ? 0.3 : 1, boxShadow: report ? '0 4px 15px rgba(16,185,129,0.25)' : 'none' }}
                  >
                    <Download size={16} /> Download PDF
                  </button>

                  {total === 0 && (
                    <span style={{ color: 'rgba(244,63,94,0.7)', fontSize: '11px', fontWeight: '500' }}>* No calls recorded</span>
                  )}
                </div>

                {/* Report Output */}
                <div style={{ width: '100%', maxWidth: '780px', alignSelf: 'center', flex: 1, overflowY: 'auto', padding: '0 8px', minHeight: 0, textAlign: 'left', maxHeight: '380px' }} className="details-table-scroll-container">
                  {report ? (
                    <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '20px', paddingBottom: '20px' }}>
                      {report.fullReport
                        ? report.fullReport.split(/\n(?=## \d+\.)/).filter(Boolean).map((section, i) => {
                            const lines = section.trim().split('\n');
                            const heading = lines[0].replace(/^## \d+\.\s*/, '').trim();
                            const body = lines.slice(1).join('\n').trim();
                            const color = SECTION_COLORS[i % SECTION_COLORS.length];
                            return (
                              <div key={i} style={{ background: 'rgba(255,255,255,0.02)', borderRadius: '12px', padding: '16px 20px', border: '1px solid rgba(255,255,255,0.04)' }}>
                                <h3 style={{ color, fontSize: '14px', fontWeight: '700', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                                  <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: color, flexShrink: 0 }} />
                                  {i + 1}. {heading}
                                </h3>
                                <MarkdownSection text={body} color={color} />
                              </div>
                            );
                          })
                        : (
                          <>
                            <div style={{ background: 'rgba(255,255,255,0.02)', borderRadius: '12px', padding: '16px 20px', border: '1px solid rgba(255,255,255,0.04)' }}>
                              <h3 style={{ color: '#8b5cf6', fontSize: '14px', fontWeight: '700', marginBottom: '8px' }}>Summary Overview</h3>
                              <p style={{ color: 'rgba(255,255,255,0.6)', fontSize: '13px', lineHeight: '1.6' }}>{report.summary}</p>
                            </div>
                            <div style={{ background: 'rgba(255,255,255,0.02)', borderRadius: '12px', padding: '16px 20px', border: '1px solid rgba(255,255,255,0.04)' }}>
                              <h3 style={{ color: '#10b981', fontSize: '14px', fontWeight: '700', marginBottom: '8px' }}>Insights & Conclusion</h3>
                              <p style={{ color: 'rgba(255,255,255,0.6)', fontSize: '13px', lineHeight: '1.6' }}>{report.conclusion}</p>
                            </div>
                          </>
                        )
                      }
                    </div>
                  ) : (
                    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', opacity: 0.15, textAlign: 'center' }}>
                      <Sparkles size={60} style={{ marginBottom: '20px' }} />
                      <p style={{ fontSize: '18px', fontWeight: '700' }}>Select a date and click generate</p>
                    </div>
                  )}
                </div>

              </div>
            </Panel>
          </div>
        </div>

      </div>
    </div>
  );
};